services:
  app:
    container_name: app
    tty: true
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    command: ["npm", "run", "start:dev"]
    ports:
      - "8888:8888"
    environment:
      QUEUE_URL: ${QUEUE_URL}
      QUEUE_NAME: ${QUEUE_NAME}
    depends_on:
      - localstack

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      EDGE_PORT: ${EDGE_PORT}
      SERVICES: sqs,s3
      DEBUG: 1
    ports:
      - "4566:4566"
      - "4582:4582"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
