version: '3.9'
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    command: ["npm", "run", "start:dev"]
    volumes: 
      - app-source:/app
    environment:
      QUEUE_URL: ${QUEUE_URL}
      QUEUE_NAME: ${QUEUE_NAME}
    depends_on:
      - localstack

  consumer:
    tty: true
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    command: ["npm", "run", "start:consumer"]
    volumes: 
      - app-source:/app
    environment:
      QUEUE_URL: ${QUEUE_URL}
      QUEUE_NAME: ${QUEUE_NAME}
    depends_on:
      - localstack
  
  localstack:
    image: localstack/localstack:latest
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      EDGE_PORT: ${EDGE_PORT}
      SERVICES: sqs,s3
      DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/tmp/localstack