services:
  app:
    container_name: app
    tty: true
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    command: ["npm", "run", "start:dev"]
    volumes:
      - app-source:/app
    environment:
      QUEUE_URL: ${QUEUE_URL}
      QUEUE_NAME: ${QUEUE_NAME}
    depends_on:
      - localstack

  localstack:
    container_name: localstack
    build:
      context: .
      dockerfile: .docker/localstack/Dockerfile
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
