apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resize-deploy
  name: resize-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resize-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: resize-deploy
    spec:
      containers:
      - image: 317884193661.dkr.ecr.eu-west-1.amazonaws.com/resize-cluster:17b68d7d05238fc32c0eaf00e0497598d2be17ce
        name: resize-api
        ports:
          - containerPort: 8888 
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8888
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthy
            port: 8888
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: resize-cm
              key: AWS_DEFAULT_REGION
        - name: QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: resize-cm
              key: QUEUE_NAME
        - name: QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: resize-cm
              key: QUEUE_URL
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: resize-cm
              key: BUCKET_NAME
        - name: BUCKET_NAME_TMP
          valueFrom:
            configMapKeyRef:
              name: resize-cm
              key: BUCKET_NAME_TMP
status: {}