name: Test and lint

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp .env.dist .env
          cp docker-compose.override.yml.dist docker-compose.override.yml
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose-ci.yml"
          test-container: "app"
          test-command: "npm test"
