name: Test and lint

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker/docker-compose.yml"
          test-container: "container1"
          test-command: "npm test"
      - run: |
          cp .env.dist .env
          cp docker-compose.override.yml.dist docker-compose.override.yml
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    # Checkout the repository
  #    - uses: actions/checkout@v2

  #    # Build the Docker image
  #    - name: Build the image
  #      run: |
  #        docker-compose build -t app .
  #    # Run linting in a Docker container
  #    - name: Run linting
  #      run: |
  #        docker-compose run -v $(pwd):/app -w /app app npm run lint
